version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.35.1
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.173.24
    - 3.173.28
    - 3.174.0
    - 3.174.1
    - 3.175.0
    - 3.175.1
    - 3.175.2
    - 3.175.3
    - 3.176.2
    - 3.176.3
    - 3.176.4
    - 3.176.6
    - 3.176.7
    - 3.176.8
    - 3.177.0
    - 3.178.0
    - 3.178.1
    - 3.178.10
    - 3.178.11
    - 3.178.2
    - 3.178.3
    - 3.178.4
    - 3.178.5
    - 3.178.6
    - 3.178.7
    - 3.178.8
    - 3.178.9
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
    - 8.2.9
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: laravel-mix
    versions:
    - 6.0.16
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.13.13
