#!/bin/bash

case "$1" in
'up')
    shift 1
    docker-compose up -d
;;
'down')
    shift 1
    docker-compose down
;;
'build')
    shift 1
    docker-compose build "$@"
;;
'composer')
    shift 1
    docker-compose exec php composer "$@"
;;
'artisan')
    shift 1
    docker-compose exec php ./artisan "$@"
;;
'phpunit')
    shift 1
    docker-compose exec php ./vendor/bin/phpunit -d memory_limit=-1 "$@"
;;
'cs')
    shift 1
    docker-compose exec php ./vendor/bin/phpcs ./app --standard=PSR12 "$@"
;;
'larastan')
    shift 1
    docker-compose exec php ./vendor/bin/phpstan analyse -c ./phpstan.neon --memory-limit=4000M
;;
'npm')
    shift 1
    docker-compose exec php npm "$@"
;;
'api_specs')
    shift 1
    npx speccy serve .api/muka-developers.v1.yaml &
;;
'close_specs')
    shift 1
    pkill -f speccy
;;
esac
