name: test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mukaapp/dev-env-php:v1
    env:
      APP_KEY: base64:cgnG+m6Mw9npiIBLIQQwzEhk9d99PK9MwwKv/UJCHfY=
      APP_URL: https://muka.local
      CACHE_DRIVER: memcached
      MEMCACHED_HOST: memcached
      MEMCACHED_PERSISTENT_ID: sessions
      MEMCACHED_PORT: 11211
      SESSION_DRIVER: memcached
      SESSION_STORE: memcached
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install -n --prefer-dist --no-scripts
        shell: sh

      - name: PHP CodeSniffer
        run: ./vendor/bin/phpcs ./app --standard=PSR12
        shell: sh

      - name: Larastan
        run: vendor/bin/phpstan analyse -c ./phpstan.neon --memory-limit=4000M
        shell: sh
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mukaapp/dev-env-php:v1
    env:
      APP_KEY: base64:cgnG+m6Mw9npiIBLIQQwzEhk9d99PK9MwwKv/UJCHfY=
      APP_URL: https://muka.local
      CACHE_DRIVER: memcached
      DB_CONNECTION: mysql
      DB_HOST: testingdb
      DB_PORT: 3306
      DB_DATABASE: mukav2
      DB_USERNAME: mukav2
      DB_PASSWORD: mukav2
      MEMCACHED_HOST: memcached
      MEMCACHED_PERSISTENT_ID: sessions
      MEMCACHED_PORT: 11211
      SESSION_DRIVER: memcached
      SESSION_STORE: memcached
    services:
      memcached:
        image: memcached
        ports:
          - '11211:11211'
      testingdb:
        image: mysql:8.0.20
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: mukav2
          MYSQL_PASSWORD: mukav2
          MYSQL_DATABASE: mukav2
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install PHP Dependencies
        run: composer install -n --prefer-dist --no-scripts
        shell: sh

      - name: PHPUnit
        run: php ./vendor/bin/phpunit
        shell: sh

#  node:
#    runs-on: ubuntu-latest
#    needs: lint
#    container:
#      image: podcastdotco/docker-php-dev-matchmaker:latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@master
#
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.7.0
#        with:
#          access_token: ${{ github.token }}
#
#      - name: Restore Node Cache
#        id: restore-cache
#        uses: actions/cache@v1
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
#      - name: Install Node Dependencies
#        run: npm install
#        shell: sh
#
#      - name: Npm test
#        run: npm test
#        shell: sh